version: '3'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
  taskqueue:
    image: ftmcloud-task-queue:latest
    container_name: ftmcloud-task-queue
    environment:
      - RABBITMQ_URI_ENCODED=
      - REDIS_URI_ENCODED=
      - MONGO_URI_ENOCDED=
  db:
    image: mongo
    container_name: ftmcloud-mongodb
    environment:
      - MONGO_INITDB_USER_PASSWORD=test123

networks:
  default:
    driver: bridge
